sonar.projectKey=traefik-route53-companion
sonar.projectName=traefik-route53-companion
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/static/**,**/*.html,**/node_modules/**
sonar.python.version=3.11
