name: SonarQube Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    runs-on: [self-hosted, docker-srv-03]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        env:
          HOST_WORKSPACE: /home/engineer/Docker/containers/github-runner/traefik-route53-companion/work/traefik-route53-companion/traefik-route53-companion
        run: |
          docker run --rm \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -e SONAR_HOST_URL=http://172.16.1.247:9000 \
            -v "${HOST_WORKSPACE}:/usr/src" \
            sonarsource/sonar-scanner-cli:latest
